version: "{build}"

image: Visual Studio 2015

# Build only on tags
skip_non_tags: true

environment:
  matrix:
    - ARCH: x64
    - ARCH: x86

matrix:
  fast_finish: true

# Shallow clone cannot be used when using git-submodule
shallow_clone: false

build:
  verbosity: minimal

before_build:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%'
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" install'

build_script:
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" build'

after_build:
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" package'

test_script:
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" test'

artifacts:
  - path: gvim_*_x86.zip
    name: gVim_x86
  - path: gvim_*_x86_pdb.zip
    name: gVim_x86_pdb
  - path: gvim_*_x64.zip
    name: gVim_x64
  - path: gvim_*_x64_pdb.zip
    name: gVim_x64_pdb
  - path: gvim_*_x86.exe
    name: gVim_x86_installer
  - path: gvim_*_x86-mui2.exe
    name: gVim_x86_mui2_installer
  - path: gvim_*_x64.exe
    name: gVim_x64_installer
  - path: gvim_*_x64-mui2.exe
    name: gVim_x64_mui2_installer

before_deploy:
  - for /f "delims=" %%i in (gitlog.txt) do set GITLOG=%%i
  # Remove the first 'v' from the tag name.
  - set VIMVER=%APPVEYOR_REPO_TAG_NAME:~1%
  - set URL=https://github.com/%APPVEYOR_REPO_NAME%/releases/download

deploy:
  - provider: GitHub
    description: |
      ![Github Downloads (by Release)](https://img.shields.io/github/downloads/$(APPVEYOR_REPO_NAME)/$(APPVEYOR_REPO_TAG_NAME)/total.svg)
      Nightly Vim Windows build snapshots ([more information](http://vim.wikia.com/wiki/Where_to_download_Vim)).

      ### Changes:

      $(GITLOG)

      ### Files:

      * [gvim_$(VIMVER)_x64-mui2.exe]($(URL)/$(APPVEYOR_REPO_TAG_NAME)/gvim_$(VIMVER)_x64-mui2.exe)
        **Experimental**: 64-bit installer with the modern interface (MUI2)
      * [gvim_$(VIMVER)_x64.zip]($(URL)/$(APPVEYOR_REPO_TAG_NAME)/gvim_$(VIMVER)_x64.zip)
        64-bit zip archive
      * [gvim_$(VIMVER)_x64_pdb.zip]($(URL)/$(APPVEYOR_REPO_TAG_NAME)/gvim_$(VIMVER)_x64_pdb.zip)
        pdb files for debugging the corresponding 64-bit executable
      * [gvim_$(VIMVER)_x86-mui2.exe]($(URL)/$(APPVEYOR_REPO_TAG_NAME)/gvim_$(VIMVER)_x86-mui2.exe)
        **Experimental**: 32-bit installer with the modern interface (MUI2)
      * [gvim_$(VIMVER)_x86.exe]($(URL)/$(APPVEYOR_REPO_TAG_NAME)/gvim_$(VIMVER)_x86.exe)
        **Recommended**: 32-bit installer
      * [gvim_$(VIMVER)_x86.zip]($(URL)/$(APPVEYOR_REPO_TAG_NAME)/gvim_$(VIMVER)_x86.zip)
        32-bit zip archive
      * [gvim_$(VIMVER)_x86_pdb.zip]($(URL)/$(APPVEYOR_REPO_TAG_NAME)/gvim_$(VIMVER)_x86_pdb.zip)
        pdb files for debugging the corresponding 32-bit executable

      ### Compiled with:

      * [Strawberry Perl](http://strawberryperl.com/) 5.28
      * [ActiveTcl](http://www.activestate.com/activetcl/downloads) 8.6.6
      * [LuaBinaries](http://luabinaries.sourceforge.net/download.html) 5.3
      * [Python](https://www.python.org/downloads/) 2.7
      * [Python3](https://www.python.org/downloads/) 3.7
      * [Racket](https://download.racket-lang.org/) 6.10.1
      * [RubyInstaller2](http://rubyinstaller.org/downloads/) 2.4

      See the [README](https://github.com/vim/vim-win32-installer/blob/master/README.md) for detail.
    auth_token:
      # Update the following key, once this is merged to Vim main repository:
      secure: kH0D/3t+1Mc8OChKhe+voKlMO0aMwnlUr64QoZOJC6BaVwy+Us3ZHq9Oo+aBzjYc
    artifact: /gVim/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

cache:
  - downloads -> appveyor.bat

# vim: ts=2 sw=2 et
