name: Publish to WinGet Stable
on:
  release:
    types: [released]
jobs:
  check-update-job:
    runs-on: ubuntu-latest
    outputs:
      needs_update: ${{ steps.check-updates.outputs.result }}
    steps:
      - name: Check updates
        id: check-updates
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LAST_RUN=$(gh run list --workflow winget_stable.yml -L 1 -s success >/dev/null 2>&1 |awk '{print $3}')
          LAST_STABLE_RELEASE=$(if echo $LAST_RUN |grep -qs '\.' >/dev/null; then echo "$LAST_RUN" | tr -d '\.v'; else echo "0"; fi)
          LAST_STABLE_RELEASE=$(( ${LAST_STABLE_RELEASE} + 200 ))
          echo "LAST_STABLE_RELEASE $LAST_STABLE_RELEASE"
          gh release list -L 1
          LAST_RELEASE=$(gh release list -L 1 |awk '{print $1}'|tr -d '.v')
          LAST_RELEASE="901665"
          echo "LAST_RELEASE $LAST_RELEASE"
          echo "result=$([[ ${LAST_RELEASE} -gt ${LAST_STABLE_RELEASE} ]] && echo true)" >> "$GITHUB_OUTPUT"

  publish-winget-stable:
    runs-on: windows-latest # action can only be run on windows
    needs: check-update-job
    if: needs.check-update-job.outputs.needs_update == 'true'
    steps:
#      - uses: vedantmgoyal2009/winget-releaser@v2
#        with:
#          identifier: vim.vim
#          installers-regex: 'gvim.*(x64|x86).exe$'
#          token: ${{ secrets.WINGET_TOKEN }}

      - name: Result
        run: |
           echo "Ready to go!"
